name: toml-check

on:
  push:
    branches:
      - main
  pull_request:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
    toml-check:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Dump GitHub context
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
          run: echo "$GITHUB_CONTEXT"
        - name: Check Arena TOML
          run: echo "hello"
        - name: Check Gauntlet TOML
          run: echo "world"
        